# Generated by Django 5.2.5 on 2025-09-13 15:48

import django.db.models.deletion
from django.db import migrations, models


def create_modulo_niveis(apps, schema_editor):
    Modulo = apps.get_model('core', 'Modulo')
    Nivel = apps.get_model('core', 'Nivel')

    # M1 - Comunicação e Linguagem
    m1 = Modulo.objects.create(nome="M1", descricao="Comunicação e Linguagem")
    Nivel.objects.create(modulo=m1, nome="N1", descricao="contato visual, resposta ao nome, emissão de sons, imitação vocal simples.")
    Nivel.objects.create(modulo=m1, nome="N2", descricao="uso de palavras isoladas, pedir itens (mandos), nomear objetos.")
    Nivel.objects.create(modulo=m1, nome="N3", descricao="frases simples, responder perguntas, relatar acontecimentos.")

    # M2 - Habilidades Sociais
    m2 = Modulo.objects.create(nome="M2", descricao="Habilidades Sociais")
    Nivel.objects.create(modulo=m2, nome="N1", descricao="brincar paralelo, aceitar aproximação, seguir instruções simples.")
    Nivel.objects.create(modulo=m2, nome="N2", descricao="brincadeira compartilhada, turnos, empatia inicial.")
    Nivel.objects.create(modulo=m2, nome="N3", descricao="jogos em grupo, cooperação, conversação.")

    # Repita este padrão para os módulos M3 a M6...
    m3 = Modulo.objects.create(nome="M3", descricao="Habilidades Cognitivas / Acadêmicas")
    Nivel.objects.create(modulo=m3, nome="N1", descricao="pareamento, cores, formas, encaixe.")
    Nivel.objects.create(modulo=m3, nome="N2", descricao="números, letras, sequências, pré-leitura.")
    Nivel.objects.create(modulo=m3, nome="N3", descricao="leitura funcional, contas simples, problemas.")

    m4 = Modulo.objects.create(nome="M4", descricao="Habilidades Motoras")
    Nivel.objects.create(modulo=m4, nome="N1", descricao="motricidade grossa (pular, correr, arremessar).")
    Nivel.objects.create(modulo=m4, nome="N2", descricao="motricidade fina (usar lápis, cortar, montar blocos).")
    Nivel.objects.create(modulo=m4, nome="N3", descricao="coordenação avançada (esportes, escrita cursiva).")

    m5 = Modulo.objects.create(nome="M5", descricao="Autonomia / Atividades de Vida Diária")
    Nivel.objects.create(modulo=m5, nome="N1", descricao="higiene simples (lavar mãos, comer sozinho).")
    Nivel.objects.create(modulo=m5, nome="N2", descricao="vestir-se, usar banheiro, guardar brinquedos.")
    Nivel.objects.create(modulo=m5, nome="N3", descricao="autonomia maior (escovar dentes sem ajuda, arrumar cama, preparar lanche).")

    m6 = Modulo.objects.create(nome="M6", descricao="Comportamento Adaptativo")
    Nivel.objects.create(modulo=m6, nome="N1", descricao="tolerar espera, reduzir birras simples.")
    Nivel.objects.create(modulo=m6, nome="N2", descricao="seguir regras, controlar frustração em contextos variados.")
    Nivel.objects.create(modulo=m6, nome="N3", descricao="resolução de conflitos, autocontrole em ambientes sociais complexos.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5)),
                ('descricao', models.TextField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='core.modulo')),
            ],
            options={
                'unique_together': {('modulo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='core.paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_emitidos', to='core.profissional')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='core.nivel')),
            ],
        ),
        migrations.RunPython(create_modulo_niveis, migrations.RunPython.noop),
    ]
