# Generated by Django 5.2.5 on 2025-09-07 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='nome_da_crianca',
        ),
        migrations.AddField(
            model_name='profissional',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], default='outro', max_length=10),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(choices=[('psicologo', 'Psicólogo'), ('psiquiatra', 'Psiquiatra'), ('fonoaudiologo', 'Fonoaudiólogo'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_profissional', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='parentesco',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pai'), (2, 'Mãe'), (5, 'Tio(a)'), (6, 'Irmão(ã)'), (7, 'Outro')], default=7, verbose_name='Parentesco'),
        ),
    ]
