# Generated by Django 5.2.5 on 2025-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_responsavel_nome_da_crianca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2020)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], default='outro', max_length=10)),
                ('descricao', models.TextField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissionais', models.ManyToManyField(blank=True, related_name='pacientes_atendidos', to='core.profissional')),
                ('responsaveis', models.ManyToManyField(related_name='pacientes_cuidados', to='core.responsavel')),
            ],
        ),
    ]
