# Generated by Django 5.2.5 on 2025-09-13 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modulo_nivel_diagnostico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_horario_fim', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_criadas', to='core.profissional')),
            ],
        ),
    ]
