# Generated by Django 5.2.5 on 2026-03-04 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_criado_em_paciente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='core.nivel'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('correta', 'Correta'), ('ajuda', 'Ajuda'), ('incorreta', 'Incorreta'), ('sem_resposta', 'Sem Resposta')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profissional')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='core.sessao')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.responsavel')),
            ],
        ),
    ]
