# Generated by Django 5.2.5 on 2026-03-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sessao_nivel_atividade_auditlog_execucaoatividade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='licenca',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='telefone',
        ),
        migrations.AddField(
            model_name='profissional',
            name='anos_experiencia_aba',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anos de Experiência em ABA'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='arquivo_curriculo',
            field=models.FileField(blank=True, null=True, upload_to='profissionais/documentos/', verbose_name='Currículo/Certificados (PDF)'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='bio_descricao',
            field=models.TextField(blank=True, help_text='Fale um pouco sobre sua atuação e abordagem...', verbose_name='Bio / Descrição Profissional'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='certificacoes',
            field=models.CharField(blank=True, help_text='Liste suas certificações principais', max_length=255, verbose_name='Certificações (BCBA, QBA, etc)'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidade_principal',
            field=models.CharField(blank=True, help_text='Ex: Psicólogo, Terapeuta Ocupacional', max_length=100, verbose_name='Especialidade Principal'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='formacao_academica',
            field=models.TextField(blank=True, help_text='Descreva sua graduação e pós-graduações...', verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='registro_profissional',
            field=models.CharField(blank=True, help_text='Ex: CRP 06/123456', max_length=50, verbose_name='Registro Profissional (CRP/CRM/etc)'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='genero',
            field=models.CharField(blank=True, help_text='Genero', max_length=25, verbose_name='Genero'),
        ),
    ]
