# Generated by Django 5.2.5 on 2026-03-05 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='responsaveis/fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='genero',
            field=models.CharField(blank=True, help_text='Genero', max_length=25, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='parentesco',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pai'), (2, 'Mãe'), (5, 'Tio(a)'), (6, 'Irmão(ã)'), (7, 'Outro')], default=7, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsavel', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
