# Generated by Django 5.2.5 on 2026-03-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_responsavel_cpf_responsavel_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Foto do Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, help_text='Genero', max_length=25, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
