# Generated by Django 5.2.5 on 2026-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_foto_paciente_alter_paciente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaoatividade',
            name='status',
            field=models.CharField(choices=[('sem_auxilio', 'Correta'), ('ajuda', 'Precisou Ajuda'), ('dificuldade', 'Teve Dificuldade'), ('nao_realizou', 'Não Realizou'), ('outro', 'Outro')], max_length=20),
        ),
    ]
