# Generated by Django 5.2.5 on 2026-03-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_execucaoatividade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='atendimento_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_logradouro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='N°'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='profissionais/documentos/', verbose_name='Curriculum Vitae'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='profissionais/documentos/', verbose_name='Diploma'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato'),
        ),
    ]
