# Generated by Django 5.2.5 on 2026-03-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profissional_atendimento_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario_proposta', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_agendamento', to='core.nivel')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_agendamento', to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_agendamento_recebidos', to='core.profissional')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_agendamento_criados', to='core.responsavel')),
                ('sessao_criada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_agendamento', to='core.sessao')),
            ],
        ),
    ]
