from .auth_serializer import RegistroSerializer
from .usuario_serializer import UsuarioSerializer
from .profissional_serializer import ProfissionalSerializer
from .responsavel_serializer import ResponsavelSerializer
from .paciente_serializer import PacienteSerializer
from .diagnostico_serializer import DiagnosticoSerializer
